@startuml

(Thing) <|-- (Countable\nConcept)
(Thing) <|-- (Technical\nElement)
(Thing) <|-- (Quantifiable\nConcept)
(Thing) <|-- (Provisioning)
(Thing) <|-- (Unit)

(Unit) <|-- (Frequency\nUnit)
(Unit) <|-- (Storage\nUnit)
(Unit) <|-- (Transfer Rate\nUnit)

(Frequency\nUnit) <|-- (MHz)
(Frequency\nUnit) <|-- (GHz)
(Storage\nUnit) <|-- (MB)
(Storage\nUnit) <|-- (GB)
(Storage\nUnit) <|-- (TB)
(Storage\nUnit) <|-- (KB)
(Transfer Rate\nUnit) <|-- (BitPerSecond)
(Transfer Rate\nUnit) <|-- (KBPerSecond)
(Transfer Rate\nUnit) <|-- (MBPerSecond)
(Transfer Rate\nUnit) <|-- (GBPerSecond)

(Technical\nElement) <|-- (Framework)
(Technical\nElement) <|-- (Provider)
(Technical\nElement) <|-- (Caching)
(Technical\nElement) <|-- (Monitoring)
(Technical\nElement) <|-- (Protocol)
(Technical\nElement) <|-- (Network)
(Technical\nElement) <|-- (Security)
(Technical\nElement) <|-- (Database)
(Technical\nElement) <|-- (OS)
(Technical\nElement) <|-- (Application\nServer)
(Technical\nElement) <|-- (Language)
(Technical\nElement) <|-- (Provider)
(Technical\nElement) <|-- (Monitoring)
(Technical\nElement) <|-- (Security)
(Technical\nElement) <|-- (Network)

(Monitoring) <|-- (Scout)
(Monitoring) <|-- (Librato)
(Monitoring) <|-- (Pingdom)

(Security) <|-- (SSL)
(Security) <|-- (SecurityKey)

(Network) <|-- (Fixie)
(Network) <|-- (Proximo)
(Network) <|-- (PointDNS)

(Framework) <|-- (Spring)
(Framework) <|-- (Rails)
(Framework) <|-- (Play)
(Framework) <|-- (Node.js)

(Language) <|-- (Java)
(Language) <|-- (Ruby)
(Language) <|-- (Python)
(Language) <|-- (Go)
(Language) <|-- (JavaScript)
(Language) <|-- (Clojure)
(Language) <|-- (C)

(Provisioning) <|-- (Resource)
(Resource) <|-- (Memory)
(Resource) <|-- (CPU Cores)
(Resource) <|-- (Bandwidth)
(Resource) <|-- (Storage)

(Quantifiable\nConcept) <|-- (Bandwidth)
(Quantifiable\nConcept) <|-- (Storage)
(Quantifiable\nConcept) <|-- (Memory)
(Quantifiable\nConcept) <|-- (MHz)
(Quantifiable\nConcept) <|-- (GHz)
(Quantifiable\nConcept) <|-- (MB)
(Quantifiable\nConcept) <|-- (GB)
(Quantifiable\nConcept) <|-- (TB)
(Quantifiable\nConcept) <|-- (KB)
(Quantifiable\nConcept) <|-- (BitPerSecond)
(Quantifiable\nConcept) <|-- (KBPerSecond)
(Quantifiable\nConcept) <|-- (MBPerSecond)
(Quantifiable\nConcept) <|-- (GBPerSecond)
(Countable\nConcept) <|-- (CPU Cores)
(Countable\nConcept) <|-- (Virtual\nMachine)

(Virtual\nMachine) ..> (Resource)
(Virtual\nMachine) ..> (OS)
(OS) <|-- (Ubuntu\nServer)
(OS) <|-- (Windows\nServer)

(Provider) <|-- (Heroku)
(Provider) <|-- (Google App\nEngine)
(Provider) <|-- (AmazonEC2)

(Database) <|-- (SQL)
(Database) <|-- (NoSQL)
(SQL) <|-- (Postgres)
(SQL) <|-- (ClearDB)
(NoSQL) <|-- (Redis)
(NoSQL) <|-- (MongoDB)

(Postgres) ..> (DatabaseSize)
(ClearDB) ..> (DatabaseSize)
(Redis) ..> (DatabaseSize)
(MongoDB) ..> (DatabaseSize)

(Quantifiable\nConcept) <|-- (DatabaseSize)

(Monitoring) <|-- (Fixie)
(Monitoring) <|-- (Proximo)
(Monitoring) <|-- (PointDNS)

(Caching) <|-- (Memcache)
(Caching) <|-- (Ironcache)

(Application\nSerer) <|-- (Tomcat)
(Application\nSerer) <|-- (Jetty)

(Countable\nConcept) <|-- (Tomcat)
(Countable\nConcept) <|-- (Jetty)

@enduml