@startuml

FeatureModel *--> "1" root

Feature <|-- root
Feature *-- "0..*" Feature : subFeatures

class Feature {
name: string
}

Feature <|-- OrFeature
OrFeature <|-- XorFeature

class Cardinality {
min: int
max: int
}

Cardinality <|-- GroupCardinality
Cardinality <|-- FeatureCardinality

class Attribute {
name: string
value: string
}

Feature *--> "0..*" Attribute: attributes
Feature *--> "1" FeatureCardinality
OrFeature *--> "2..*" Feature : variants
OrFeature --> GroupCardinality

FeatureModel *--> "0..*" Constraint

Constraint <|-- Operation
Operator <|-- And
Operator <|-- Or
Operator <|-- Implies
Operator <|-- Not

Operation --> "1" ConstrainableElement : from
Operation --> "0..1" ConstrainableElement : to
Operation --> "1" Operator: op

class Element {
value: int
}

ConstrainableElement <|-- Element
ConstrainableElement <|-- Operation

Element *--> "1" Feature : feature

@enduml